apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: notefy-ingress
  namespace: staging
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # Added to fix "Mixed Content" and proxy headers
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Forwarded-Proto https;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - staging-notefy.ramtiin.ir
    secretName: notefy-staging-tls
  rules:
  - host: staging-notefy.ramtiin.ir
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: notefy-service
            port:
              number: 80