apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../base
  - ingress.yaml
  - secrets.yaml

labels:
  - includeSelectors: true
    pairs:
      app: notefy
      environment: staging

images:
  - name: ramtiin/notefy
    newTag: staging-3827ad4b3aff3894306745413fa3dc9f579a2ceb

patches:
  - target:
      kind: Deployment
      name: notefy
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1