apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../production/deployment.yaml
  - ../production/postgres.yaml
  - ingress.yaml
  - secrets.yaml

labels:
  - includeSelectors: true
    pairs:
      app: notefy
      environment: staging

images:
  - name: ramtiin/notefy
    newTag: staging-bb5df4dec4a338a7287a758bfaa3604eb74f4d66

patches:
  - target:
      kind: Deployment
      name: notefy
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "128Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "100m"
  - target:
      kind: PersistentVolumeClaim
      name: postgres-pvc
    patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: 5Gi