apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../base
  - ingress.yaml
  - secrets.yaml

labels:
  - includeSelectors: true
    pairs:
      app: notefy
      environment: staging

images:
  - name: ramtiin/notefy
    newTag: staging-9cf8879f93b1183fe312a55e7dc3e74f63a6284f

patches:
  - target:
      kind: Deployment
      name: notefy
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1