apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: staging
type: Opaque
data:
  # Values: notefy / your_password / notefy (Base64 encoded)
  POSTGRES_USER: bm90ZWZ5
  POSTGRES_PASSWORD: eW91cl9wYXNzd29yZA==
  POSTGRES_DB: bm90ZWZ5