apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: staging
type: Opaque
data:
  # Values: notefy / your_password / notefy (Base64 encoded)
  postgres-user: bm90ZWZ5
  postgres-password: eW91cl9wYXNzd29yZA==
  postgres-db: bm90ZWZ5