apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - ../base
  - ingress.yaml
  - secrets.yaml
  - backup-cronjob.yaml

labels:
  - includeSelectors: true
    pairs:
      app: notefy
      environment: production

images:
  - name: ramtiin/notefy
    newTag: production-latest

patches:
  - target:
      kind: Deployment
      name: notefy
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3